
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



const AdminUsersPage = lazy(() => import("./pages/AdminUsersPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const ForgotPasswordPage = lazy(() => import("./pages/ForgotPasswordPage.tsx"));
const ImpressumPage = lazy(() => import("./pages/ImpressumPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const OldCaseExport = lazy(() => import("./pages/OldCaseExport.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/admin-users-page", element: <UserGuard><AdminUsersPage /></UserGuard>},
	{ path: "/adminuserspage", element: <UserGuard><AdminUsersPage /></UserGuard>},
	{ path: "/", element: <UserGuard><App /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/forgot-password-page", element: <ForgotPasswordPage />},
	{ path: "/forgotpasswordpage", element: <ForgotPasswordPage />},
	{ path: "/impressum-page", element: <ImpressumPage />},
	{ path: "/impressumpage", element: <ImpressumPage />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <Logout />},
	{ path: "/old-case-export", element: <UserGuard><OldCaseExport /></UserGuard>},
	{ path: "/oldcaseexport", element: <UserGuard><OldCaseExport /></UserGuard>},

];
